### ISSUE TITLE
Change AgeQualifyingCode for children

### ISSUE THREAD

**Issue by nikolaeva31** [happy-travel/komoro#343]
Error from supplier:
`ShortText="No Over/Under Occupancy Allowed."`

https://logs-dev.happytravel.com/app/discover#/doc/97718760-2573-11ed-bcc8-bbc1434ea904/fluentd-komoro-2022.10?id=LTyYLYQBS3UURj_2KsNZ

**Comment by DFSko** [comment]
fixed
